### ISSUE TITLE
Unintended rule interactions

### ISSUE THREAD

**Issue by roedoejet** [roedoejet/g2p#23]
Because the rules in g2p apply in sequence, and because mappings can be normalized to either NFC or NFD, some unintended bleeding and feeding interactions can happen. I think this is the root cause of some of the weird problems we were blaming on normalization before.

For example, in the `ctp -> ctp-ipa` mapping, there is a rule that transforms `kw -> kʷ`. There is also a rule that transforms `k -> kʲ`. If the first rule is ordered before the second, it will feed it and an input of `kw` will output `kʲʷ`. If the second rule is ordered before the first, it will bleed it and an input of `kw` will output `kʲw`.

The same problem can happen as a result of normalization. In `ctp-ipa -> eng-ipa`, there is a rule `õ -> õː` and `o ->  oː` which results in the same issues as with the `k` rules when normalized to NFD (but not with NFC).

Chris Cox solved this in his `tgx` mapping by creating an intermediate form like so:

```json
    { "in": "tʼ",	"out": "1R" },
    { "in": "t",	"out": "tʰ" },
    { "in": "ʼ",	"out": "ʔ" },
    { "in": "1",	"out": "t" },
    { "in": "R",	"out": "ʼ" },
```

But is this how we should recommend solving this problem? Should we check for this type of interaction (and maybe insert the intermediate forms) by default? Or should we encourage a more regex-centric approach like changing `k -> kʲ` to `k(?!ʷ) -> kʲ` and add a new syntax into the mapping files to allow for negative lookaheads/lookbehinds?

**Comment by joanise** [comment]
For fra_to_ipa I went to an intermediate representation, but I avoided characters that could occur in text - I used an IPA symbol that doesn't occur in French text of phonology and then mapped it back after the rules I needed to protect.
I don't like seeing `1R` because those two character could theoretically occur. That method does make writing the rest of the rules simpler, though, so it's not a bad way to go.
The tricky part is thinking in terms of the NFD equivalent of the rules I'm writing.

Yes, I fully support the idea of `k(?!w) -> kj` style rules, with negative assertions. That would make rule-writing a lot easier I think. The intermediate representation solution feels kludgy to me.

**Comment by roedoejet** [comment]
Right. A couple thoughts...

We could do this automatically and assign the intermediary form to be some random character from an uncommonly used Unicode block (say, `random.randrange(9632, 9727)`). We could either do this automatically if `as_is=False` or we could let individual rules be flagged so that `{ "in": "tʼ", "out": "1R" }` could be written `{ "in": "tʼ", "out": "tʼ", "prevent_feeding": true }` or something like that. 

Alternatively with the `k(?!ʷ) -> kʲ` style rules, we could write the rule as `{ "in": "k", "out": "kʲ", "context_not_after": "ʷ" }` although this also feels klunky to me.

**Comment by joanise** [comment]
You also asked:
    Should we check for this type of interaction (and maybe insert the intermediate forms) by default?

Tricky. On one hand, yes, that would be great to have happen automatically, but on the other hand it seems hard to write in a truly safe way. For French I ended up with a lot of careful sequencing of rules, which will all break if we change how they're applied. Making it an option that can be enabled with a flag would be a good idea. If I had had the option, I would have probably used it, but ended up with quite a different mapping file.

Question: is there a way to get the state of the text after the application of each rule? It would really help if I could follow step by step the transformations that my rules apply.

**Comment by roedoejet** [comment]
> Question: is there a way to get the state of the text after the application of each rule? It would really help if I could follow step by step the transformations that my rules apply.

Yes! There is a `debugger` flag that can be set to True for just that purpose. If you pull the latest version of g2p it also pretty prints the output. so `g2p convert 'bonjour' fra eng-ipa --debugger` on the command line.

> Tricky. On one hand, yes, that would be great to have happen automatically, but on the other hand it seems hard to write in a truly safe way. For French I ended up with a lot of careful sequencing of rules, which will all break if we change how they're applied. Making it an option that can be enabled with a flag would be a good idea. If I had had the option, I would have probably used it, but ended up with quite a different mapping file.

Yes, at least we could maybe write something that 'validates' the rules. That is, it checks if the output of one rule is matched by the input of another etc..either way could work, but we should have some guides in the documentation describing common rule ordering problems and how to address them

**Comment by joanise** [comment]
True, doing it automatically with `as_is=False` should be fine. 

In fact, how about going one step further: with `as_is=False`, or maybe with a more explicit global 'allow_feeding=False`, have every rule go to something intermediate, preferably in Supplementary Private Use Area A (U+F0000-U+FFFFD) or B (U+100000-U+10FFFD), so you're guaranteed there will be no collisions. "rarely used" is not never used, while "Private Use" is explicitly reserved for this kind of purpose. However, MSWord leaves stuff in the first Private Use Area, which is why I'm suggesting the supplementary ones. This is simple to implement, no heuristics or tricky logic to detect when it's needed, systematically break every rule into two and tell the user the output of each rule is final and cannot be modified again.
That would be a lot easier to wrap my brain around when writing rules, and I could rely on the logic that longer rules are applied first, so write the rules for the exceptions explicitly, then write the shorter rules for the general cases.
I really like this idea.

**Comment by joanise** [comment]
> Yes, at least we could maybe write something that 'validates' the rules.
Still tricky. Take this contrived example:
```
a->bc
d->ef
ce->g
```

Then `ad` will go to `bcef` and then `bgf`. And `ae` will go to `bce` and then `ge`. Feeding interacts with the context of the output of a rule, so such validation might just not be feasible.

**Comment by joanise** [comment]
Oh, and instead of random, use U+(F0000 + index number of the rule), so the characters used are sequential and encode the rule number they come from.

**Comment by joanise** [comment]
OK, I'm excited about this whole idea. The more I think about it, the more I'm convinced a global `prevent_feeding=True` flag (via systematic use of private use characters) would be a game changer is the resulting simplicity of writing rules. It's cognitively much easier to think about what I want in the final output for a given input.

**Comment by roedoejet** [comment]
> Then `ad` will go to `bcef` and then `bgf`. And `ae` will go to `bce` and then `ge`. Feeding interacts with the context of the output of a rule, so such validation might just not be feasible.

Hmm, yes, good point. I'll have to think about this a bit more.

> OK, I'm excited about this whole idea. The more I think about it, the more I'm convinced a global prevent_feeding=True flag (via systematic use of private use characters) would be a game changer is the resulting simplicity of writing rules. It's cognitively much easier to think about what I want in the final output for a given input.

Yes, I really like this too!

> Oh, and instead of random, use U+(F0000 + index number of the rule), so the characters used are sequential and encode the rule number they come from.

This is a good suggestion and much improved over just random, but I think this might still cause problems for the indexing. We would need the output and the intermediate form to be of equal length. Nevermind, as I'm writing I guess we could just do U+(F0000 + index number of the rule) * each character in the output string. *thinking out loud*. That way there's a unique intermediate form and the length/indices are still preserved.

**Comment by joanise** [comment]
> comments about the indexing problem

How is preserving the length of the output going to help the indexing problem? Rules can still change the length of the string from the input to the output, so that's still going to have to be handled. Nonetheless, turning `a->bc` into `a->PP` followed by `PP->bc` would work (where P stands for the private use char for this rule), if that helps with the indexing problem. 

Have you already written the code that solves the indexing problem, and are trying to not have to solve it again?

**Comment by roedoejet** [comment]
> Have you already written the code that solves the indexing problem, and are trying to not have to solve it again?

Yes, it already preserves indices (which was a pain) so I would prefer to not have to change that part.

> Nonetheless, turning a->bc into a->PP followed by PP->bc would work (where P stands for the private use char for this rule), if that helps with the indexing problem.

This is actually what I was trying to propose above (perhaps unclearly). But yes, I think this would work.

**Comment by roedoejet** [comment]
> I still want to be able to have this as false and do it for individual rules, but that's not implemented yet.

Done as of dd3dfe9e0411ea2c36a7ea07469b001ba1a7e464

**Comment by roedoejet** [comment]
@joanise do you think we should still implement the negative lookahead/lookbehind functionality? I don't want to clutter the rule making process, and this solution would require adding two more columns to each mapping CSV, and increase the clutter in the g2p studio. Can we get away with just positive lookahead/lookbehinds + feeding prevention?

**Comment by littell** [comment]
> OK, I'm excited about this whole idea. The more I think about it, the more I'm convinced a global `prevent_feeding=True` flag (via systematic use of private use characters) would be a game changer is the resulting simplicity of writing rules. It's cognitively much easier to think about what I want in the final output for a given input.

> Ok, as of b618dbb you should be able to put prevent_feeding = true in your mapping config to globally create an intermediate form for each rule now

Oh, very cool, good idea guys!

**Comment by joanise** [comment]
First gotcha I just noticed:
```
s,z,Vowels,Vowels
```
is now harder to implement since I don't know if the context will be the original vowels or their intermediary representation.

Ditto a rule that would say `e followed by two Consonant goes to ɛ`, which leads to another related question: how do I say that macro like `Consonant` defined in `fra_abbs.csv` should occur twice consecutively in the context?

**Comment by roedoejet** [comment]
> is now harder to implement since I don't know if the context will be the original vowels or their intermediary representation.

Hm, yes, this makes sense. There are usually at least some feeding relationships that you *want*. I think I'll be using the rule-specific feeding prevention more than the global one for that reason.

> how do I say that macro like Consonant defined in fra_abbs.csv should occur twice consecutively in the context?

Currently there is no way. I guess the easiest way of doing this right now would be in the g2p studio. You could create some blocks that double each consonant in the variable Consonant and make rules for each of them. This is probably a rare example of where it's actually easier for the lay person to make a rule than for the programmer. We could introduce some regex style syntax like Vowels{2} or something like that but I'm also a little wary of getting too deep into just replicating regex functionality.

**Comment by joanise** [comment]
Hum, one more issue: `\b` no longer works as expected. I have `ng,ŋ,,\b` to change word-final "ng" to /ŋ/, but it's kicking in mid word in "manger", because my rule for `"er"->/e/` kicked in first, and I'm guessing the `\b` considers private use characters as non-word characters, hence a boundary in this case. Ugh.

**Comment by joanise** [comment]
> I think I'll be using the rule-specific feeding prevention

Is that implemented yet, and how do I use it with `.csv` rules? (I fear you'll say I need to use `.json` to turn in on...)

**Comment by roedoejet** [comment]
> Hum, one more issue: \b no longer works as expected. I have ng,ŋ,,\b to change word-final "ng" to /ŋ/, but it's kicking in mid word in "manger", because my rule for "er"->/e/ kicked in first, and I'm guessing the \b considers private use characters as non-word characters, hence a boundary in this case. Ugh.

This is definitely a pain. I guess it could be a reason to venture into a different Unicode block, but that has its own set of problems.

> (I fear you'll say I need to use .json to turn in on...)
😬

**Comment by roedoejet** [comment]
> (I fear you'll say I need to use .json to turn in on...)

Maybe yaml is the best of all worlds? Or you're really set on csv? With yaml anyways we can have it be a bit more readable, include comments, and have arbitrary keys like `prevent_feeding`.

**Comment by roedoejet** [comment]
> Hum, one more issue: \b no longer works as expected. I have ng,ŋ,,\b to change word-final "ng" to /ŋ/, but it's kicking in mid word in "manger", because my rule for "er"->/e/ kicked in first, and I'm guessing the \b considers private use characters as non-word characters, hence a boundary in this case. Ugh.

What about just putting `(^|\s)` in place of `\b`. Truth be told, I basically never use `\b` because it's totally unreliable for most orthographies.

**Comment by joanise** [comment]
> What about just putting `(^|\s)` in place of `\b`.

I thought about using that overnight, it would certainly be simpler. I had tried with `$`, but that didn't work, presumably because `($|\s)` is what I needed there.

> Maybe yaml is the best of all worlds? Or you're really set on csv?

I'm willing to use whatever I have to use, it's just that I like the conciseness of csv. Do you have a converter that writes json or yaml from csv? (I know, I can write a one-liner to do it, it's not hard, but if you already have it, that would be even more convenient.)

My inclination with things like this is hybrid solutions, like supporting a json string of additional flags in a 5th column of the csv, but that's kind of ugly, so you probably don't want to do that, especially since the commas in the json would be parsed as csv separators. Never mind.

There are plenty of csv and json samples in the g2p repo, do you have a yaml sample anywhere yet? I have to agree, that's a format with minimal superfluous punctuation, so it would not be too painful to work with. On the other hand, json would let me pack one whole rule per line since it is punctuation-delimited rather than newline-delimited.

Anyway, I assume the yaml will look something like this:
```
 - in: a
   out: b
   prevent_feeding: true
 - in: c
   out: d
   context_before: f
   context_after: (\s|$)
```

**Comment by joanise** [comment]
> how do I say that macro like Consonant defined in fra_abbs.csv should occur twice consecutively in the context?

Found it: `(Consonant)(Consonant)` works.

**Comment by roedoejet** [comment]
> Found it: (Consonant)(Consonant) works.

Oh cool! I'd never used that before. I guess it makes sense. The variables just get expanded to a | joined string.

> There are plenty of csv and json samples in the g2p repo, do you have a yaml sample anywhere yet?

No, yaml isn't currently supported. But I see no reason not to support it. I was thinking of something along the lines of your example yaml above too.

> Do you have a converter that writes json or yaml from csv?

No, I don't have that built in. The rules that can be expressed in csv are a subset of those that can be expressed in json or yaml though, so I agree we should have a conversion tool, but we should give some warnings about that too.
